name = "cardbored"
compatibility_date = "2024-01-15"
pages_build_output_dir = "dist"

# KV binding for Scryfall bulk data
# To create the namespace, run: npx wrangler kv:namespace create "CARD_DB"
# Then replace the IDs below with the output from that command
[[kv_namespaces]]
binding = "CARD_DB"
id = "REPLACE_WITH_PRODUCTION_NAMESPACE_ID"
preview_id = "REPLACE_WITH_PREVIEW_NAMESPACE_ID"

[env.production]
name = "cardbored"