permissions:
  contents: write
  
name: Update Card Data

on:
  # Run daily at 6 AM UTC (when Scryfall typically updates)
  schedule:
    - cron: '0 6 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update even if no changes detected'
        required: false
        default: 'false'
        type: boolean

  # Run on push to main (for testing)
  push:
    branches: [ main ]
    paths-ignore:
      - 'scripts/public/cards.json'
      - 'dist/**'

jobs:
  update-cards:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Fetch latest card data
      run: npm run fetch-cards
      env:
        NODE_ENV: production
    
    - name: Check for changes
      id: check-changes
      run: |
        if git diff --quiet scripts/public/cards.json; then
          echo "No changes detected in card data"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Card data has been updated"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Build project
      if: steps.check-changes.outputs.has_changes == 'true' || github.event.inputs.force_update == 'true'
      run: npm run build
    
    - name: Commit and push changes
      if: steps.check-changes.outputs.has_changes == 'true' || github.event.inputs.force_update == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add scripts/public/cards.json dist/cards.json
        git commit -m "🤖 Auto-update card data $(date -u +'%Y-%m-%d %H:%M UTC')" || exit 0
        git push
    
    - name: Deploy to Cloudflare Pages
      if: steps.check-changes.outputs.has_changes == 'true' || github.event.inputs.force_update == 'true'
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: cardbored
        directory: dist
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Notify completion
      if: always()
      run: |
        if [ "${{ steps.check-changes.outputs.has_changes }}" == "true" ]; then
          echo "✅ Card data successfully updated and deployed!"
        else
          echo "ℹ️ No card data changes detected - skipping deployment"
        fi
